server:
  port : 8081
spring:
  datasource:
    url: jdbc:mysql://vipal994.beget.tech/vipal994_blog?useSSL=false&serverTimezone=Europe/Moscow
    username: vipal994_blog
    password: sava1812!
  jpa:
    hibernate:
      ddl-auto: update